### ISSUE TITLE
reward validator with extra tokens so they get more market power for validating well, not wei

### ISSUE THREAD

**Issue by jessicagmarshall** [distribute-protocol/distribute-contracts#31]

**Comment by jessicagmarshall** [comment]
write a function in DistributeToken.sol that can only be called by TokenRegistry.sol during reward validator that increments total supply of tokens as well as incrementing transfer from escrow functionality

**Comment by shkfnly** [comment]
are we sure we want to do this?

**Comment by jessicagmarshall** [comment]
yes - @ssircar and @ArianaFreitag brought up good points about this today

**Comment by jessicagmarshall** [comment]
they're concerned about there being enough wei in the pool to reward the proposer and validators
